"""Distinctiveness gate for memory->code symbol linking.

MARM links a concept entity to a code symbol when the entity's name matches a
symbol name exactly (`link_method: exact_symbol`, confidence 1.0). Exactness is
not the same as aboutness: in a repository with tens of thousands of symbols,
ordinary English words match something almost every time.

Observed on a 31,452-node repo, every one of the six links produced was a
coincidence of this kind:

    upload    -> a Swift method          actions  -> the .github/actions folder
    update    -> a Kotlin method         updates  -> a var in dependabot.yml
    toml      -> a var in Cargo.toml     criterion-> a var in Cargo.toml

None of those memories were about those symbols. A wrong link is worse than no
link, because it is presented at confidence 1.0 next to the code it names.

The gate answers one question: could this name plausibly be a reference to a
specific symbol? A name earns a link if it LOOKS like an identifier, or if it is
at least not an everyday word.
"""

from __future__ import annotations

import re

# Words that match a symbol in almost any large repository, so their matching
# says nothing about what a memory is about. Deliberately broad: the cost of
# excluding a real reference is one missing link, while the cost of admitting
# one of these is a confident falsehood attached to a file path.
_COMMON = {
    "about",
    "action",
    "actions",
    "active",
    "add",
    "added",
    "admin",
    "after",
    "again",
    "agent",
    "alert",
    "all",
    "allow",
    "also",
    "always",
    "api",
    "app",
    "apply",
    "args",
    "array",
    "asset",
    "assets",
    "async",
    "audit",
    "auth",
    "auto",
    "back",
    "bad",
    "base",
    "batch",
    "before",
    "begin",
    "best",
    "beta",
    "block",
    "body",
    "book",
    "bool",
    "both",
    "branch",
    "break",
    "buffer",
    "build",
    "builds",
    "button",
    "bytes",
    "cache",
    "call",
    "calls",
    "cancel",
    "case",
    "change",
    "changes",
    "channel",
    "check",
    "checks",
    "child",
    "class",
    "clean",
    "clear",
    "click",
    "client",
    "clients",
    "clone",
    "close",
    "cloud",
    "code",
    "color",
    "column",
    "command",
    "commands",
    "comment",
    "comments",
    "commit",
    "commits",
    "common",
    "config",
    "configs",
    "connect",
    "content",
    "contents",
    "context",
    "copy",
    "core",
    "count",
    "create",
    "current",
    "cursor",
    "custom",
    "data",
    "database",
    "date",
    "debug",
    "default",
    "defaults",
    "delete",
    "deps",
    "detail",
    "details",
    "dev",
    "device",
    "diff",
    "dir",
    "disable",
    "display",
    "doc",
    "docs",
    "done",
    "down",
    "download",
    "draft",
    "edge",
    "edit",
    "email",
    "empty",
    "enable",
    "end",
    "engine",
    "entry",
    "env",
    "error",
    "errors",
    "event",
    "events",
    "exec",
    "exit",
    "export",
    "extra",
    "fail",
    "failed",
    "false",
    "fetch",
    "field",
    "fields",
    "file",
    "files",
    "filter",
    "final",
    "find",
    "first",
    "fix",
    "fixed",
    "fixes",
    "flag",
    "flags",
    "flow",
    "focus",
    "folder",
    "font",
    "form",
    "format",
    "frame",
    "free",
    "from",
    "full",
    "func",
    "function",
    "get",
    "git",
    "global",
    "good",
    "graph",
    "group",
    "guide",
    "handle",
    "handler",
    "hash",
    "head",
    "header",
    "headers",
    "height",
    "help",
    "hide",
    "home",
    "hook",
    "hooks",
    "host",
    "html",
    "http",
    "icon",
    "image",
    "images",
    "import",
    "index",
    "info",
    "init",
    "input",
    "inputs",
    "insert",
    "install",
    "int",
    "item",
    "items",
    "job",
    "jobs",
    "join",
    "json",
    "key",
    "keys",
    "label",
    "last",
    "layer",
    "layout",
    "left",
    "level",
    "lib",
    "line",
    "lines",
    "link",
    "links",
    "list",
    "load",
    "local",
    "lock",
    "log",
    "logs",
    "loop",
    "main",
    "major",
    "make",
    "map",
    "mark",
    "mask",
    "match",
    "max",
    "media",
    "memory",
    "menu",
    "merge",
    "message",
    "messages",
    "meta",
    "method",
    "methods",
    "min",
    "minor",
    "mode",
    "model",
    "module",
    "more",
    "move",
    "name",
    "names",
    "new",
    "next",
    "node",
    "nodes",
    "none",
    "note",
    "notes",
    "null",
    "number",
    "object",
    "off",
    "offset",
    "old",
    "open",
    "option",
    "options",
    "order",
    "out",
    "output",
    "outputs",
    "over",
    "own",
    "package",
    "page",
    "pages",
    "panel",
    "param",
    "params",
    "parent",
    "parse",
    "parser",
    "part",
    "password",
    "patch",
    "path",
    "paths",
    "pause",
    "pending",
    "pipeline",
    "plan",
    "plugin",
    "plugins",
    "point",
    "pool",
    "port",
    "post",
    "prefix",
    "prepare",
    "preview",
    "print",
    "process",
    "profile",
    "project",
    "projects",
    "prompt",
    "props",
    "public",
    "pull",
    "push",
    "query",
    "queue",
    "quick",
    "range",
    "rate",
    "read",
    "ready",
    "record",
    "ref",
    "refs",
    "region",
    "release",
    "releases",
    "remote",
    "remove",
    "render",
    "repo",
    "repos",
    "report",
    "reports",
    "request",
    "requests",
    "reset",
    "resolve",
    "response",
    "result",
    "results",
    "retry",
    "return",
    "review",
    "reviews",
    "right",
    "role",
    "root",
    "route",
    "router",
    "routes",
    "row",
    "rows",
    "rule",
    "rules",
    "run",
    "running",
    "runs",
    "same",
    "save",
    "scale",
    "scan",
    "schema",
    "scope",
    "score",
    "script",
    "scripts",
    "search",
    "second",
    "section",
    "select",
    "send",
    "server",
    "service",
    "services",
    "session",
    "set",
    "settings",
    "setup",
    "shape",
    "share",
    "shell",
    "show",
    "side",
    "sign",
    "simple",
    "size",
    "skip",
    "slot",
    "small",
    "snapshot",
    "sort",
    "source",
    "space",
    "spec",
    "speed",
    "split",
    "stack",
    "stage",
    "start",
    "state",
    "static",
    "stats",
    "status",
    "step",
    "steps",
    "stop",
    "storage",
    "store",
    "stream",
    "string",
    "strip",
    "struct",
    "style",
    "styles",
    "sub",
    "submit",
    "success",
    "suite",
    "summary",
    "support",
    "sync",
    "syntax",
    "system",
    "table",
    "tag",
    "tags",
    "target",
    "task",
    "tasks",
    "team",
    "temp",
    "template",
    "templates",
    "test",
    "tests",
    "text",
    "theme",
    "thread",
    "time",
    "timeout",
    "title",
    "toggle",
    "token",
    "tokens",
    "tool",
    "tools",
    "top",
    "total",
    "trace",
    "track",
    "true",
    "type",
    "types",
    "unit",
    "units",
    "update",
    "updates",
    "upload",
    "uploads",
    "url",
    "usage",
    "use",
    "used",
    "user",
    "users",
    "util",
    "utils",
    "valid",
    "validate",
    "value",
    "values",
    "version",
    "versions",
    "view",
    "views",
    "wait",
    "warn",
    "warning",
    "watch",
    "web",
    "width",
    "window",
    "work",
    "worker",
    "workflow",
    "workflows",
    "write",
    "yaml",
    "yml",
    "toml",
    "json5",
    "xml",
    "csv",
    "sql",
    "drop",
    "popup",
    "description",
    "permissions",
    "features",
    "changelog",
    "readme",
    "license",
    "contributing",
    "overview",
}

_NUMERIC = re.compile(r"^[vV]?[\d.\-_+→>]+$")
_CODE_SHAPED = re.compile(r"[_.]|::|[a-z][A-Z]|^[A-Z][a-z]+[A-Z]")


def is_linkable(name: str) -> bool:
    """True when `name` could plausibly be a reference to a specific symbol."""
    if not isinstance(name, str):
        return False
    text = name.strip()
    if not text or len(text) < 3:
        return False
    # A symbol reference is one token. "11 Open PRs" and "48 Cargo.toml Files
    # Across Project Structure" are sentence fragments the extractor kept whole.
    if any(ch.isspace() for ch in text):
        return False
    # Bare numbers and version strings: "0.15", "11", "2.0", "0.5→0.8", "v1.8.2".
    if _NUMERIC.match(text):
        return False
    # An identifier shape is positive evidence, and outranks the stoplist:
    # `update_state` and `UpdateState` are specific where `update` is not.
    # Note this also admits `_update` and `__update__`, since `_CODE_SHAPED`
    # matches a bare underscore. That is intended -- a leading underscore is a
    # private-symbol convention, so the name really is an identifier -- but it
    # means nothing containing `_` ever reaches the stoplist below.
    if _CODE_SHAPED.search(text):
        return True
    return text.casefold() not in _COMMON


# A memory is rarely "about" a heading in a README or a directory. These kinds
# are structural artefacts the indexer records, not symbols a memory refers to,
# and matching them produced Changelog -> README.md and popup -> a folder.
NON_SYMBOL_LABELS = {"section", "folder", "file", "project", "branch", "module"}


def is_symbol_label(label: object) -> bool:
    """True when a matched node is a real code symbol rather than structure."""
    if not isinstance(label, str) or not label.strip():
        return True  # unlabelled: let the name gate decide
    return label.strip().casefold() not in NON_SYMBOL_LABELS
